'use strict';
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const PORT=Number(process.env.PORT||3000), DATA=process.env.DATA_FILE||path.join(__dirname,'data','store.json');
const statuses=['new','confirmed','preparing','ready','out_for_delivery','delivered','cancelled'];
const defaults={name:"Leo's Cafe",phone:'0347-0390716',whatsapp:'923470390716',address:'Chak Shehzad, Islamabad',latitude:null,longitude:null,open:'12:00',close:'23:00',deliveryMinutes:50,deliveryFee:0,deliveryRadiusKm:5,timezone:'Asia/Karachi',acceptingOrders:true};
const menu=[
['Chicken Fajita Pizza','Pizza',500],['Bonfire Pizza','Pizza',500],['Supreme Pizza','Pizza',500],['Chicken Lover Pizza','Pizza',500],['Cheese Lover Pizza','Pizza',500],['Tex-Mexican Pizza','Pizza',500],['White Castle Pizza','Pizza',550],['Malai Boti Pizza','Pizza',550],['Behari Kabab Pizza','Pizza',550],['Cheese Crust Pizza','Pizza',550],['Kabab Crust Pizza','Pizza',550],['Shahi Pizza','Pizza',550],['Labistro Pizza','Pizza',550],['Crown Crust Pizza','Pizza',550],
['Zinger Burger','Burgers',440],['Leo’s Cafe Special Zinger','Burgers',500],['Chicken Pattie Burger','Burgers',300],['Chapli Kabab Burger','Burgers',300],['Tower Burger','Burgers',550],['Zinger Tower Burger','Burgers',600],['Pizza Burger','Burgers',450],['Zinger Strip (Boneless)','Chicken',240],['Chicken Nuggets (5 Pcs)','Chicken',240],['Oven Baked Wings (8 Pcs)','Chicken',470],['Hot Wings (8 Pcs)','Chicken',470],['Twister Roll','Rolls',300],['Tikka Roll','Rolls',300],['Chapli Kabab Roll','Rolls',300],['Chicken Pattie Roll','Rolls',300],['Seekh Kabab Roll','Rolls',300],['Salted Fries','Fries',300],['Loaded Fries','Fries',470],['Cheese Fries','Fries',520],['Leo’s Special Pasta','Pasta',450],
['Deal 1 · Zinger Burger + 5 Pcs Nuggets','Deals',640],['Deal 2 · 3 Zinger Burgers + 1 Ltr Drink','Deals',1430],['Deal 3 · 2 Medium Pizzas + 1.5 Ltr Drink','Deals',2400],['Deal 4 · 2 Small Pizzas + Zinger Burger + 1 Ltr Drink','Deals',1950],['Deal 5 · 1 Large Pizza + 6 Wings + 1.5 Ltr Drink','Deals',2060],['Deal 6 · 1 Large Pizza + 1.5 Ltr Drink','Deals',1990]
].map(([name,category,price],i)=>({id:`item-${i+1}`,name,category,price,available:true}));
function initial(){return {settings:defaults,menu,users:[],orders:[],sessions:[],otps:[],audit:[]};}
let db;try{db=JSON.parse(fs.readFileSync(DATA,'utf8'));}catch(e){if(e.code!=='ENOENT')throw e;db=initial();persist();}
function persist(){fs.mkdirSync(path.dirname(DATA),{recursive:true});let tmp=DATA+'.tmp';fs.writeFileSync(tmp,JSON.stringify(db,null,2),{mode:0o600});fs.renameSync(tmp,DATA);}
const id=()=>crypto.randomUUID(),now=()=>new Date().toISOString(),hash=s=>crypto.createHash('sha256').update(s).digest('hex');
const pass=(s,salt=crypto.randomBytes(16).toString('hex'))=>`${salt}:${crypto.pbkdf2Sync(s,salt,210000,32,'sha256').toString('hex')}`;
function validPass(s,stored){if(!stored)return false;let [salt,digest]=stored.split(':');let calc=pass(s,salt).split(':')[1];return crypto.timingSafeEqual(Buffer.from(digest,'hex'),Buffer.from(calc,'hex'));}
function phone(v){let p=String(v||'').replace(/\D/g,'');if(p.startsWith('92'))p='0'+p.slice(2);assert(/^03\d{9}$/.test(p),'Pakistan mobile number 03XXXXXXXXX likhein.');return p;}
function publicUser(u){let {passwordHash,...safe}=u;return safe;}
function auth(req){let token=(req.headers.cookie||'').match(/(?:^|; )session=([^;]+)/)?.[1];let session=db.sessions.find(s=>s.tokenHash===hash(token||'')&&s.expires>Date.now());return db.users.find(u=>u.id===session?.userId);}
function reply(res,status,data,extra={}){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...extra});res.end(JSON.stringify(data));}
function assert(x,msg,status=400){if(!x){let e=Error(msg);e.status=status;throw e;}}
function role(u,...roles){assert(u,'Login required.',401);assert(roles.includes(u.role),'Access denied.',403);}
function body(req){return new Promise((resolve,reject)=>{let b='';req.on('data',c=>{b+=c;if(b.length>100000){reject(Object.assign(Error('Request too large'),{status:413}));req.destroy();}});req.on('end',()=>{try{resolve(b?JSON.parse(b):{});}catch{reject(Error('Invalid JSON'));}});req.on('error',reject);});}
const rate=new Map();function throttle(key,limit=8,window=600000){let t=Date.now(),v=(rate.get(key)||[]).filter(x=>x>t-window);assert(v.length<limit,'Too many attempts; try later.',429);v.push(t);rate.set(key,v);}
async function sms(destination,message){let sid=process.env.TWILIO_ACCOUNT_SID,token=process.env.TWILIO_AUTH_TOKEN,from=process.env.TWILIO_FROM;
 if(sid&&token&&from){let params=new URLSearchParams({To:'+92'+destination.slice(1),From:from,Body:message});let r=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${sid}/Messages.json`,{method:'POST',headers:{Authorization:'Basic '+Buffer.from(sid+':'+token).toString('base64'),'Content-Type':'application/x-www-form-urlencoded'},body:params});assert(r.ok,'SMS provider failed.',502);return;}
 assert(process.env.NODE_ENV!=='production','SMS provider is not configured.',503);console.log(`[DEV OTP] ${destination}: ${message}`);
}
async function sendOtp(number,purpose){throttle('otp:'+number,4,3600000);let code=String(crypto.randomInt(100000,1000000));let record={phone:number,purpose,digest:hash(code),expires:Date.now()+300000,attempts:0};db.otps=db.otps.filter(o=>!(o.phone===number&&o.purpose===purpose));db.otps.push(record);persist();await sms(number,`Leo's Cafe code: ${code}. Expires in 5 minutes.`);}
function verifyOtp(number,purpose,code){let o=db.otps.find(x=>x.phone===number&&x.purpose===purpose);assert(o&&o.expires>Date.now()&&o.attempts<5,'Code expired. Request a new code.');o.attempts++;persist();assert(/^\d{6}$/.test(String(code))&&crypto.timingSafeEqual(Buffer.from(o.digest,'hex'),Buffer.from(hash(String(code)),'hex')),'Invalid code.');db.otps=db.otps.filter(x=>x!==o);persist();}
function session(res,u){let token=crypto.randomBytes(32).toString('hex');db.sessions.push({tokenHash:hash(token),userId:u.id,expires:Date.now()+30*86400000});persist();res.setHeader('Set-Cookie',`session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=2592000${process.env.COOKIE_SECURE==='true'?'; Secure':''}`);}
function log(actor,action,ref){db.audit.push({at:now(),actor:actor.id,action,ref});if(db.audit.length>2000)db.audit.shift();}
function ensureAdmin(){let username=process.env.ADMIN_USER,password=process.env.ADMIN_PASSWORD,number=process.env.ADMIN_PHONE;if(!db.users.some(u=>u.role==='admin')&&username&&password&&number){assert(password.length>=6,'ADMIN_PASSWORD too short');db.users.push({id:id(),role:'admin',name:'Admin',username,phone:phone(number),passwordHash:pass(password),points:0,completedOrders:0,createdAt:now()});persist();console.log('Admin account initialized.');}}
ensureAdmin();
function openNow(){let s=db.settings;if(!s.acceptingOrders)return false;let time=new Intl.DateTimeFormat('en-GB',{timeZone:s.timezone||'Asia/Karachi',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date());return s.open<=s.close?time>=s.open&&time<s.close:time>=s.open||time<s.close;}
function scopedOrder(o,u){return {...o,riderLocation:u.role==='customer'&&o.status!=='out_for_delivery'?null:o.riderLocation};}
async function api(req,res,url){let method=req.method,route=url.pathname,u=auth(req),b=['POST','PATCH','DELETE'].includes(method)?await body(req):{};
 if(method==='GET'&&route==='/api/public')return reply(res,200,{settings:db.settings,open:openNow(),menu:db.menu.filter(x=>x.available)});
 if(method==='GET'&&route==='/api/me')return reply(res,200,{user:u?publicUser(u):null});
 if(method==='POST'&&route==='/api/otp/request'){let number=phone(b.phone),purpose=b.purpose==='reset'?'reset':'register';if(purpose==='reset')assert(db.users.some(x=>x.phone===number&&x.role==='admin'),'Contact cafe management to recover access.');await sendOtp(number,purpose);return reply(res,200,{ok:true,message:'Code sent if SMS service is configured.'});}
 if(method==='POST'&&route==='/api/register'){let number=phone(b.phone);verifyOtp(number,'register',b.code);assert(!db.users.some(x=>x.phone===number),'Phone already registered.');assert(String(b.name||'').trim().length>=2,'Name required.');assert(String(b.password||'').length>=8,'Password must have at least 8 characters.');let u2={id:id(),name:String(b.name).trim().slice(0,80),phone:number,role:'customer',riderRequested:b.accountType==='rider',passwordHash:pass(b.password),address:String(b.address||'').slice(0,250),latitude:null,longitude:null,points:0,completedOrders:0,createdAt:now()};db.users.push(u2);persist();session(res,u2);return reply(res,201,{user:publicUser(u2)});}
 if(method==='POST'&&route==='/api/login'){throttle('login:'+(req.socket.remoteAddress||''),25);let identity=String(b.identity||'');let found=db.users.find(x=>x.username===identity||x.phone===identity);assert(found&&validPass(String(b.password||''),found.passwordHash),'Invalid credentials.',401);session(res,found);return reply(res,200,{user:publicUser(found)});}
 if(method==='POST'&&route==='/api/logout'){let token=(req.headers.cookie||'').match(/(?:^|; )session=([^;]+)/)?.[1];db.sessions=db.sessions.filter(s=>s.tokenHash!==hash(token||''));persist();res.setHeader('Set-Cookie','session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return reply(res,200,{ok:true});}
 if(method==='POST'&&route==='/api/reset'){let number=phone(b.phone);verifyOtp(number,'reset',b.code);assert(String(b.password||'').length>=8,'Password too short.');let target=db.users.find(x=>x.phone===number&&x.role==='admin');assert(target,'Admin not found.');target.passwordHash=pass(b.password);db.sessions=db.sessions.filter(s=>s.userId!==target.id);log(target,'password_reset',target.id);persist();return reply(res,200,{ok:true});}
 role(u,'admin','rider','customer');
 if(method==='PATCH'&&route==='/api/profile'){u.name=String(b.name||u.name).trim().slice(0,80);u.address=String(b.address||'').slice(0,250);for(let key of ['latitude','longitude'])if(b[key]===null||Number.isFinite(Number(b[key])))u[key]=b[key]===null?null:Number(b[key]);persist();return reply(res,200,{user:publicUser(u)});}
 if(method==='GET'&&route==='/api/orders'){let orders=db.orders.filter(o=>u.role==='admin'||o.customerId===u.id||(u.role==='rider'&&(o.riderId===u.id||o.status==='ready'))).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));return reply(res,200,{orders:orders.map(o=>scopedOrder(o,u))});}
 if(method==='POST'&&route==='/api/orders'){role(u,'customer');assert(openNow(),'Cafe is closed for online orders.');assert(Array.isArray(b.items)&&b.items.length>0&&b.items.length<31,'Select items.');let items=b.items.map(x=>{let product=db.menu.find(m=>m.id===x.id&&m.available),qty=Number(x.qty);assert(product&&Number.isInteger(qty)&&qty>0&&qty<=20,'Invalid item or quantity.');return {id:product.id,name:product.name,qty,price:product.price};});let address=String(b.address||u.address||'').trim();assert(address.length>=8,'Delivery address required.');let subtotal=items.reduce((v,x)=>v+x.price*x.qty,0),lat=b.latitude===null?null:Number(b.latitude),lon=b.longitude===null?null:Number(b.longitude);let o={id:id(),number:'LC-'+String(Date.now()).slice(-8),customerId:u.id,customerName:u.name,customerPhone:u.phone,address:address.slice(0,250),latitude:Number.isFinite(lat)&&lat>=-90&&lat<=90?lat:null,longitude:Number.isFinite(lon)&&lon>=-180&&lon<=180?lon:null,items,subtotal,deliveryFee:Number(db.settings.deliveryFee)||0,total:subtotal+(Number(db.settings.deliveryFee)||0),paymentMethod:'cash',status:'new',riderId:null,riderLocation:null,createdAt:now(),updatedAt:now(),estimatedAt:new Date(Date.now()+Number(db.settings.deliveryMinutes||50)*60000).toISOString(),events:[{at:now(),status:'new'}],pointsAwarded:0};db.orders.push(o);log(u,'order_created',o.id);persist();return reply(res,201,{order:scopedOrder(o,u)});}
 let match=route.match(/^\/api\/orders\/([^/]+)\/(status|location)$/);if(method==='PATCH'&&match){let o=db.orders.find(x=>x.id===match[1]);assert(o,'Order not found.',404);if(match[2]==='location'){role(u,'rider');assert(o.riderId===u.id&&o.status==='out_for_delivery','Active delivery required.',403);let lat=Number(b.latitude),lon=Number(b.longitude);assert(Number.isFinite(lat)&&lat>=-90&&lat<=90&&Number.isFinite(lon)&&lon>=-180&&lon<=180,'Invalid coordinates.');o.riderLocation={latitude:lat,longitude:lon,at:now()};o.updatedAt=now();persist();return reply(res,200,{ok:true});}
 role(u,'admin','rider');let next=String(b.status),old=o.status;assert(statuses.includes(next),'Unknown status.');if(u.role==='rider'){assert(o.riderId===u.id||old==='ready'&&next==='out_for_delivery','Order not assigned.',403);assert(old==='ready'&&next==='out_for_delivery'||old==='out_for_delivery'&&next==='delivered','Invalid rider transition.');if(!o.riderId)o.riderId=u.id;}else{let allowed={new:['confirmed','cancelled'],confirmed:['preparing','cancelled'],preparing:['ready','cancelled'],ready:['out_for_delivery','cancelled'],out_for_delivery:['delivered','cancelled']};assert((allowed[old]||[]).includes(next),'Invalid status change.');if(next==='out_for_delivery'){let rider=db.users.find(x=>x.id===b.riderId&&x.role==='rider');assert(rider,'Choose an approved rider.');o.riderId=rider.id;}}
 o.status=next;o.updatedAt=now();o.events.push({at:now(),status:next,by:u.id});if(next==='out_for_delivery')o.departedAt=now();if(next==='delivered'){o.deliveredAt=now();o.riderLocation=null;let c=db.users.find(x=>x.id===o.customerId);c.completedOrders=(c.completedOrders||0)+1;if(c.completedOrders%10===0){c.points=(c.points||0)+50;o.pointsAwarded=50;}}if(next==='cancelled')o.riderLocation=null;log(u,'order_status_'+next,o.id);persist();return reply(res,200,{order:o});}
 if(method==='POST'&&route==='/api/redeem'){role(u,'customer');assert(u.points>=1000,'1000 points required.');let pizza=db.menu.find(x=>x.id===b.itemId&&x.category==='Pizza'&&x.available&&x.price<=1450);assert(pizza,'Choose an available pizza.');assert(openNow(),'Cafe is closed.');let address=String(b.address||u.address||'').trim();assert(address.length>=8,'Delivery address required.');u.points-=1000;let o={id:id(),number:'LC-'+String(Date.now()).slice(-8),customerId:u.id,customerName:u.name,customerPhone:u.phone,address:address.slice(0,250),latitude:u.latitude||null,longitude:u.longitude||null,items:[{id:pizza.id,name:pizza.name,qty:1,price:0}],subtotal:0,deliveryFee:Number(db.settings.deliveryFee)||0,total:Number(db.settings.deliveryFee)||0,paymentMethod:'cash',status:'new',riderId:null,riderLocation:null,redemptionPoints:1000,createdAt:now(),updatedAt:now(),estimatedAt:new Date(Date.now()+Number(db.settings.deliveryMinutes||50)*60000).toISOString(),events:[{at:now(),status:'new'}],pointsAwarded:0};db.orders.push(o);log(u,'redeemed_pizza',o.id);persist();return reply(res,201,{order:o});}
 if(method==='GET'&&route==='/api/admin/menu'){role(u,'admin');return reply(res,200,{menu:db.menu});}
 if(method==='GET'&&route==='/api/admin/users'){role(u,'admin');return reply(res,200,{users:db.users.map(x=>({...publicUser(x),orderCount:db.orders.filter(o=>o.customerId===x.id).length,totalSpent:db.orders.filter(o=>o.customerId===x.id&&o.status==='delivered').reduce((n,o)=>n+o.total,0)}))});}
 if(method==='PATCH'&&route.startsWith('/api/admin/users/')){role(u,'admin');let target=db.users.find(x=>x.id===route.split('/').at(-1));assert(target&&target.role==='customer'&&target.riderRequested,'Pending rider request not found.');assert(b.approve===true,'Approval required.');target.role='rider';target.riderRequested=false;log(u,'rider_approved',target.id);persist();return reply(res,200,{user:publicUser(target)});}
 if(method==='PATCH'&&route==='/api/admin/settings'){role(u,'admin');for(let k of ['name','phone','whatsapp','address','open','close','timezone'])if(k in b)db.settings[k]=String(b[k]).slice(0,250);for(let k of ['deliveryMinutes','deliveryFee','deliveryRadiusKm'])if(k in b){let v=Number(b[k]);assert(Number.isFinite(v)&&v>=0&&v<100000,'Invalid number.');db.settings[k]=v;}for(let k of ['latitude','longitude'])if(k in b){let v=b[k]===null?null:Number(b[k]);assert(v===null||Number.isFinite(v),'Invalid coordinates.');db.settings[k]=v;}if('acceptingOrders'in b)db.settings.acceptingOrders=b.acceptingOrders===true;assert(/^\d{2}:\d{2}$/.test(db.settings.open)&&/^\d{2}:\d{2}$/.test(db.settings.close),'Invalid hours.');log(u,'settings_updated','cafe');persist();return reply(res,200,{settings:db.settings});}
 if(method==='POST'&&route==='/api/admin/menu'||method==='PATCH'&&route.startsWith('/api/admin/menu/')){role(u,'admin');let existing=method==='PATCH'?db.menu.find(x=>x.id===route.split('/').at(-1)):null;assert(method==='POST'||existing,'Item not found.',404);let name=String(b.name||existing?.name||'').trim(),category=String(b.category||existing?.category||'').trim(),price=Number(b.price??existing?.price);assert(name&&category&&Number.isInteger(price)&&price>=0&&price<100000,'Invalid item.');let item=existing||{id:id()};Object.assign(item,{name:name.slice(0,100),category:category.slice(0,60),price,available:b.available===undefined?(existing?.available??true):b.available===true});if(!existing)db.menu.push(item);log(u,'menu_updated',item.id);persist();return reply(res,200,{item});}
 if(method==='GET'&&route==='/api/admin/report'){role(u,'admin');let from=url.searchParams.get('from'),to=url.searchParams.get('to');assert(!from||/^\d{4}-\d\d-\d\d$/.test(from),'Invalid from date.');assert(!to||/^\d{4}-\d\d-\d\d$/.test(to),'Invalid to date.');let orders=db.orders.filter(o=>(!from||o.createdAt.slice(0,10)>=from)&&(!to||o.createdAt.slice(0,10)<=to)),delivered=orders.filter(o=>o.status==='delivered'),customerIds=new Set(orders.map(o=>o.customerId));return reply(res,200,{orders:orders.length,delivered:delivered.length,pending:orders.filter(o=>!['delivered','cancelled'].includes(o.status)).length,cancelled:orders.filter(o=>o.status==='cancelled').length,sales:delivered.reduce((n,o)=>n+o.total,0),cash:delivered.filter(o=>o.paymentMethod==='cash').reduce((n,o)=>n+o.total,0),customers:customerIds.size,newCustomers:db.users.filter(x=>x.role==='customer'&&x.createdAt.slice(0,10)>=(from||'0000')&&x.createdAt.slice(0,10)<=(to||'9999')).length,rows:delivered.map(o=>({number:o.number,date:o.deliveredAt,customer:o.customerName,total:o.total}))});}
 reply(res,404,{error:'Not found.'});}
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png','.json':'application/json','.svg':'image/svg+xml'};
const server=http.createServer(async(req,res)=>{try{let url=new URL(req.url,'http://localhost');if(url.pathname.startsWith('/api/')){if(!['GET','POST','PATCH','DELETE'].includes(req.method))return reply(res,405,{error:'Method not allowed.'});if(req.method!=='GET'&&req.headers.origin){let origin=new URL(req.headers.origin);assert(origin.host===req.headers.host,'Invalid origin.',403);}return await api(req,res,url);}let name=url.pathname==='/'?'/index.html':url.pathname;let target=path.resolve(__dirname,'public','.'+decodeURIComponent(name));assert(target.startsWith(path.join(__dirname,'public')+path.sep),'Invalid path.',403);let stat=fs.statSync(target);assert(stat.isFile(),'Not found.',404);res.writeHead(200,{'Content-Type':types[path.extname(target)]||'application/octet-stream','Cache-Control':name.includes('service-worker')?'no-cache':'public, max-age=3600'});fs.createReadStream(target).pipe(res);}catch(e){if(!res.headersSent)reply(res,e.status|| (e.code==='ENOENT'?404:500),{error:e.status||e.code==='ENOENT'?e.message:'Server error.'});console.error(e.status?e.message:e);}});
if(require.main===module)server.listen(PORT,()=>console.log(`Leo's Cafe running on http://localhost:${PORT}`));module.exports={server,phone,openNow};
